#!/bin/sh
#controll internet
wan_led_color1='/sys/class/leds/c50-v3:green:wan/brightness'
wan_led_color2='/sys/class/leds/c50-v3:orange:wan/brightness'

while :
	do
    stat=$(ping -q -c 1 -W 1 8.8.8.8  > /dev/null 2>&1 && echo "ok" || echo "FAIL")
    link=$(swconfig dev switch0 show | fgrep link | grep port:0 | cut -d " " -f 3| cut -d ":" -f 2)
	
    if [ "$stat" = "ok" ]; then
        echo 0 > $wan_led_color2
        echo 255 > $wan_led_color1
        else 
        if [ "$link" = "down" ]; then
            echo 0 > $wan_led_color2
            echo 0 > $wan_led_color1
            else
            echo 0 > $wan_led_color1
            echo 255 > $wan_led_color2
	    fi
    fi
	sleep 10
done
